"""Shared task defaults used by PPO and SAC."""

LIDAR_SECTOR_DIM = 16
POSE_GOAL_DIM = 7
IMU_FEATURE_DIM = 10
OCCUPANCY_GRID_SHAPE = None

MAX_STEPS = 2000
COLLISION_THRESHOLD = 0.1
LOW_SCORE_THRESHOLD = -800.0
ENDPOINT = (2.0, 0.0)
GOAL_THRESHOLD = 0.1
GOAL_STOP_SPEED_THRESHOLD = 0.1

COLLISION_PENALTY = -80.0
PROGRESS_REWARD_SCALE = 5.0
DISTANCE_REWARD_SCALE = 1.0
HEADING_REWARD_SCALE = 0.2
SAFETY_REWARD_SCALE = 0.1
MOTION_REWARD_SCALE = 0.02
NEW_BEST_DISTANCE_BONUS = 0.5
STEP_PENALTY = -0.02
GOAL_SUCCESS_REWARD = 250.0
GOAL_STOP_BONUS = 300.0
GOAL_HOLD_REWARD = 5.0
GOAL_SPEED_PENALTY = -80.0
GOAL_OVERSHOOT_PENALTY = -120.0

ENABLE_SLAM = True
PROFILE_SLAM = False
SLAM_PROFILE_INTERVAL = 500
SAVE_SLAM_PLOTS = False
FORCE_CPU = True

MAX_STEERING_ANGLE = 0.9
MAX_SPEED = 10.0
MIN_SPEED = 0.0
START_POSITION = (-2.0, 0.0, 0.02)
START_ROTATION = (0.0, 0.0, 1.0, 0.0)
START_POSITION_NOISE = 0.03
START_YAW_NOISE = 0.2
RESET_SETTLE_STEPS = 10
