"""Shared task defaults used by PPO and SAC."""

LIDAR_SECTOR_DIM = 16
POSE_GOAL_DIM = 7
IMU_FEATURE_DIM = 10
OCCUPANCY_GRID_SHAPE = None

MAX_STEPS = 2000
COLLISION_THRESHOLD = 0.1
LOW_SCORE_THRESHOLD = -80.0
ENDPOINT = (2.0, 0.0)
GOAL_THRESHOLD = 0.1
GOAL_STOP_SPEED_THRESHOLD = 0.1

COLLISION_PENALTY = -8.0
PROGRESS_REWARD_SCALE = 0.5
DISTANCE_REWARD_SCALE = 0.1
HEADING_REWARD_SCALE = 0.02
SAFETY_REWARD_SCALE = 0.01
MOTION_REWARD_SCALE = 0.002
NEW_BEST_DISTANCE_BONUS = 0.05
STEP_PENALTY = -0.002
GOAL_SUCCESS_REWARD = 25.0
GOAL_STOP_BONUS = 30.0
GOAL_HOLD_REWARD = 0.5
GOAL_SPEED_PENALTY = -8.0
GOAL_OVERSHOOT_PENALTY = -12.0
REWARD_SCALE = 0.1  # Reward scaling for numerical stability (used by both PPO and SAC)

ENABLE_SLAM = True
PROFILE_SLAM = False
SLAM_PROFILE_INTERVAL = 500
SAVE_SLAM_PLOTS = False
FORCE_CPU = True

MAX_STEERING_ANGLE = 0.9
MAX_SPEED = 10.0
MIN_SPEED = 0.0
START_POSITION = (-2.0, 0.0, 0.02)
START_ROTATION = (0.0, 0.0, 1.0, 0.0)
START_POSITION_NOISE = 0.03
START_YAW_NOISE = 0.2
RESET_SETTLE_STEPS = 10
