"""Shared task defaults used by PPO and SAC."""

LIDAR_SECTOR_DIM = 16
POSE_GOAL_DIM = 7
IMU_FEATURE_DIM = 10
OCCUPANCY_GRID_SHAPE = None

MAX_STEPS = 2000
COLLISION_THRESHOLD = 0.1
LOW_SCORE_THRESHOLD = -200.0
ENDPOINT = (2.0, 0.0)
GOAL_THRESHOLD = 0.3
GOAL_STOP_SPEED_THRESHOLD = 0.15

COLLISION_PENALTY = -35.0
PROGRESS_REWARD_SCALE = 1.2
DISTANCE_REWARD_SCALE = 0.02
HEADING_REWARD_SCALE = 0.03
SAFETY_REWARD_SCALE = 0.03
MOTION_REWARD_SCALE = 0.05
SLOW_SPEED_THRESHOLD = 0.25   # speed_norm below this (< 25 % of max = 1.5 m/s) is "too slow"
SLOW_SPEED_PENALTY = -0.04    # per-step penalty while speed_norm < SLOW_SPEED_THRESHOLD
HIGH_SPEED_THRESHOLD = 0.6    # speed_norm above this (> 60 % of max = 3.6 m/s) earns a bonus
HIGH_SPEED_BONUS = 0.03       # per-step bonus while speed_norm > HIGH_SPEED_THRESHOLD
NEW_BEST_DISTANCE_BONUS = 0.02
STEP_PENALTY = -0.003
GOAL_SUCCESS_REWARD = 60.0
GOAL_STOP_BONUS = 40.0
GOAL_HOLD_REWARD = 0.0
GOAL_SPEED_PENALTY = -10.0
GOAL_OVERSHOOT_PENALTY = -12.0
REWARD_SCALE = 0.1  # Reward scaling for numerical stability (used by both PPO and SAC)

ENABLE_SLAM = True
PROFILE_SLAM = False
SLAM_PROFILE_INTERVAL = 500
SAVE_SLAM_PLOTS = False
FORCE_CPU = True

MAX_STEERING_ANGLE = 0.9
MAX_SPEED = 6.0
MIN_SPEED = 0.0
START_POSITION = (-2.0, 0.0, 0.02)
START_ROTATION = (0.0, 0.0, 1.0, 0.0)
START_POSITION_NOISE = 0.08
START_YAW_NOISE = 0.45
RESET_SETTLE_STEPS = 10
